package Parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ifkrec = 10;
  public static final int zatvorenaviticasta = 16;
  public static final int minus = 19;
  public static final int dodela = 27;
  public static final int elsekrec = 11;
  public static final int naredbe = 12;
  public static final int konstanta = 29;
  public static final int vecejednako = 24;
  public static final int jednako = 25;
  public static final int main = 2;
  public static final int otvorenazagrada = 13;
  public static final int manje = 21;
  public static final int bool = 4;
  public static final int podeljeno = 20;
  public static final int EOF = 0;
  public static final int id = 30;
  public static final int scanf = 7;
  public static final int manjejednako = 23;
  public static final int otvorenaviticasta = 15;
  public static final int intidzer = 5;
  public static final int dvetacke = 28;
  public static final int error = 1;
  public static final int dodelatipa = 26;
  public static final int plus = 17;
  public static final int puta = 18;
  public static final int dok = 9;
  public static final int plivajuci = 6;
  public static final int var = 3;
  public static final int zatvorenazagrada = 14;
  public static final int printf = 8;
  public static final int vece = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "main",
  "var",
  "bool",
  "intidzer",
  "plivajuci",
  "scanf",
  "printf",
  "dok",
  "ifkrec",
  "elsekrec",
  "naredbe",
  "otvorenazagrada",
  "zatvorenazagrada",
  "otvorenaviticasta",
  "zatvorenaviticasta",
  "plus",
  "puta",
  "minus",
  "podeljeno",
  "manje",
  "vece",
  "manjejednako",
  "vecejednako",
  "jednako",
  "dodelatipa",
  "dodela",
  "dvetacke",
  "konstanta",
  "id"
  };
}

